blank_issues_enabled: true
contact_links:
  - name: Discussions
    url: https://github.com/ravindrareddyk/fifa-worldcup-2026-india/discussions
    about: Please use Discussions for questions, teaching ideas, and general conversation.